In [1]:
import numpy as np
import time
from numpy import zeros, ones

In [2]:
# Height & weight arrays
person_height = [6.7, 5.4, 6.7, 8.9, 4.5]
person_weight = [55, 66, 54, 78, 99]

In [3]:
height_array = np.array(person_height)
weight_array = np.array(person_weight)

In [4]:
type(height_array)
height_array


array([6.7, 5.4, 6.7, 8.9, 4.5])

In [5]:
type(weight_array)
weight_array

array([55, 66, 54, 78, 99])

In [6]:
# List comprehension
l1 = [10, 12, 15, 18, 19]
l2 = [i + 1 for i in l1]
l2

[11, 13, 16, 19, 20]

In [7]:
# NumPy array operation
arr1 = np.array(l1)
arr2 = arr1 + 1
arr2

array([11, 13, 16, 19, 20])

In [8]:
# Performance comparison
my_array = np.arange(1000000)
my_list = list(range(100000))

In [9]:
start_time = time.time()
arr3 = [i ** 2 for i in my_list]
end_time = time.time()

timediff = end_time - start_time
print("Diff between endtime and starttime:", timediff)

Diff between endtime and starttime: 0.007482767105102539


In [10]:
# Zeros array
ar1 = zeros(shape=5)
print(ar1)

[0. 0. 0. 0. 0.]


In [11]:
ar2 = zeros(shape=(5, 2))
print(ar2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
# Ones array
ar3 = ones(shape=5)
print(ar3)

[1. 1. 1. 1. 1.]


In [13]:
# Random numbers
random_data = np.random.random(10)
print(random_data)

[0.22837588 0.44067762 0.64446386 0.1023962  0.65596726 0.36005534
 0.24964452 0.66733157 0.95436173 0.86159189]


In [14]:
# Empty array
arr6 = np.empty(shape=4, dtype=float)
print(arr6)

[3.26215747e-315 0.00000000e+000 9.51815540e-307 2.93887764e-315]


In [15]:
# Correct way to create filled array
arr7 = np.full(shape=5, fill_value=0, dtype=int)
print(arr7)

[0 0 0 0 0]


In [16]:
# Identity matrix
arr8 = np.identity(4)
print(arr8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
#multidimensional array

l1 = [[1,2,3],[4,5,6]]
multi_l1 = np.array(l1)
print(multi_l1)

[[1 2 3]
 [4 5 6]]


In [18]:
t1 = ([2,4,6],[9,8,4])
multi_t1 = np.array(t1)
print(multi_t1)

[[2 4 6]
 [9 8 4]]


In [19]:
t2 = ((1,2,5),(12,45,22))
multi_t2 =np.array(t2)
print(multi_t2)

[[ 1  2  5]
 [12 45 22]]


In [20]:
#numpy attributes

quantity = np.array([[11,33,44],[22,55,11]])
print(quantity.ndim) #get dimension
print(quantity.itemsize) #get itemsize
print(quantity.dtype)# get datatype
print(quantity.shape)#get shape

2
8
int64
(2, 3)


In [21]:
#numpy methods

print("Before reshaping",quantity)
print("After reshaping",quantity.reshape(3,2))

Before reshaping [[11 33 44]
 [22 55 11]]
After reshaping [[11 33]
 [44 22]
 [55 11]]


In [22]:
#indexing

counting = np.array([11,12,4,5,44,45,66])
print(counting[0],counting[3],counting[-1])

11 5 66


In [23]:
print(quantity[1][1])
print(quantity[1])

55
[22 55 11]


In [24]:
print(quantity[0]) # get rows
print(quantity[:,0]) #get columns

[11 33 44]
[11 22]


In [25]:
price = [101,121,112,123,114]
arr_price = np.array(price)

In [26]:
print(arr_price)

[101 121 112 123 114]


In [27]:
print("slicing:",arr_price[1:4])
print("first three elements:",arr_price[0:3])
print("starting from any index value",arr_price[2:])
print("Get al value without start and stop:",arr_price[:])


slicing: [121 112 123]
first three elements: [101 121 112]
starting from any index value [112 123 114]
Get al value without start and stop: [101 121 112 123 114]


In [28]:
prices = np.array(
    [[101,102,117,109,145],
     [210,222,209,245,213],
     [90,34,99,45,65],
     [45,78,33,56,99]])
print(prices)


[[101 102 117 109 145]
 [210 222 209 245 213]
 [ 90  34  99  45  65]
 [ 45  78  33  56  99]]


In [29]:
print("Slice 2d array:",prices[1:,3:])

Slice 2d array: [[245 213]
 [ 45  65]
 [ 56  99]]


In [30]:
item_quantity = np.arange(5)

print("ading onedimen array:",arr_price + item_quantity)

ading onedimen array: [101 122 114 126 118]


In [31]:
performance_scores = np.array([9,8,4,5,6])
print(performance_scores)

[9 8 4 5 6]


In [32]:
print("sum function:",np.sum(performance_scores))
print("min function",np.min(performance_scores))
print("power function:",np.power(performance_scores,2))

sum function: 32
min function 4
power function: [81 64 16 25 36]


In [33]:
num_array = np.random.randint(1,10,(2,3))
print(num_array)
print("sum 2darray:",np.sum(num_array,axis=0))
print("min 2darray:",np.min(num_array,axis=0))

[[2 1 4]
 [2 4 8]]
sum 2darray: [ 4  5 12]
min 2darray: [2 1 4]


In [34]:
production_day_1 = np.array([11,44,55])
production_day_2 = np.array([22,44,11])

In [35]:
print("Concatenate:",np.concatenate([production_day_1,production_day_2]))

Concatenate: [11 44 55 22 44 11]


In [36]:
player_score_1 = np.array([[10,10,23],[22,13,13]])
player_score_2 = np.array([[12,45,22],[19,43,24]])
print(np.concatenate([player_score_1,player_score_2]))

[[10 10 23]
 [22 13 13]
 [12 45 22]
 [19 43 24]]


In [37]:
#stacking
num_array_1 = np.array([[2,4,5],[5,9,4]])
num_array_2 = np.array([[10,34,21],[45,32,12]])
print("num_array_1 value:",num_array_1)
print("num_array_2 value",num_array_2)

num_array_1 value: [[2 4 5]
 [5 9 4]]
num_array_2 value [[10 34 21]
 [45 32 12]]


In [38]:
print("stacking 2 arrays",np.stack([num_array_1,num_array_2],axis=1))
print("horizontal stacking 2 arrays",np.hstack([num_array_1,num_array_2]))
print("vertical stacking 2 arrays",np.vstack([num_array_1,num_array_2]))
print("depth stacking 2 arrays",np.dstack([num_array_2,num_array_1]))

stacking 2 arrays [[[ 2  4  5]
  [10 34 21]]

 [[ 5  9  4]
  [45 32 12]]]
horizontal stacking 2 arrays [[ 2  4  5 10 34 21]
 [ 5  9  4 45 32 12]]
vertical stacking 2 arrays [[ 2  4  5]
 [ 5  9  4]
 [10 34 21]
 [45 32 12]]
depth stacking 2 arrays [[[10  2]
  [34  4]
  [21  5]]

 [[45  5]
  [32  9]
  [12  4]]]


In [39]:
m1 = np.array([4])
m2 = np.array([8])
m3 = np.array([4])
m4 = np.array([4])
print("Blocking all mseries:",np.block([[m1,m2],[m3,m4]]))

Blocking all mseries: [[4 8]
 [4 4]]


In [40]:
#split vertical
my_data_array = np.arange(20.0)
my_new_array = my_data_array.reshape(4,5)
print("The reshaped array is:n",my_new_array)

The reshaped array is:n [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
